### ISSUE TITLE
`shell-command-to-string` and `call-process` don't work in an envrc world

### ISSUE THREAD

**Issue by glasserc** [purcell/envrc#12]
I'm trying to get [rust-mode](https://github.com/rust-lang/rust-mode) working on a project I'm hacking on. This project is set up using `direnv` to use a nix env that uses cargo from `nixpkgs-mozilla`. When I run `rust-test` from within a file in the project, it errors out with something like this backtrace:

```
Debugger entered--Lisp error: (file-missing "Searching for program" "No such file or directory" "cargo")
  call-process("cargo" nil t nil "locate-project")
  rust-buffer-project()
  rust-update-buffer-project()
```

The offending lines in `rust-buffer-project` can be simplified to something like `(with-temp-buffer (call-process rust-cargo-bin nil t nil "locate-project"))`.

This seemed like a lot of work to go through in order just to capture stdout of a process, so I looked around and found `shell-command-to-string`, but `(shell-command-to-string "cargo locate-project")` produces more-or-less the same behavior.

Although `shell-command-to-string` and `call-process` break, `shell-command` and `compile` work fine. I'm not 100% sure why. I'm guessing that it has to do with which buffer is "current" when the final calls to do the exec happen, but I haven't traced all the way through both functions to figure out exactly what code paths I'm hitting.

I guess my question is, what is the best practice here? Should people writing `call-process` be writing to an output buffer? Is it fair to complain to authors of packages that don't do that? It seems like mandating that developers copy `process-environment` over manually would be bad (especially since `process-environment` is described as "may be risky if used as a file-local variable").

**Comment by znewman01** [comment]
Another example: NixOS/nix-mode#120. I think I'll be able to get a workaround in, as it's a Nix-friendly project, but I'm not sure every project would go for something like that.

I wonder whether it's a good idea to supply a way to "lock in" the current environment, with which we can advise the offending functions:

```emacs-lisp
(advice-add 'rust-test :around #'envrc-freeze-environment)
```
One way to implement:

- have a variable `envrc-frozen-env` set to `nil`
- `envrc-freeze-environment` would look something like:
   ```emacs-lisp
   (defun envrc-freeze-environment (orig-func &rest args)
     (let ((envrc-frozen-env <the current buffer's env>))
       (apply orig-func args)))
   ```
-  if `envrc-frozen-env` is non-nil, `envrc` should set `process-environment` to *that* rather than the (possibly cached) `direnv` result

(There are probably better names and better ways to do this too.)

**Comment by purcell** [comment]
The basic issue here is that when working with processes in a temp buffer, any buffer-local process environment is not propagated to the temp buffer, and no hooks in the temp buffer can cause envrc to initialise the local process environment afresh.

It's a limitation of envrc-mode to some extent, but you can also plausibly argue that if the user has set up their process environment locally to their current buffer, then they should reasonably expect it to affect any processes started from that buffer, whatever the mechanism, and that breaking that promise is a bug in the corresponding package.

This affected magit and I applied the following logic to get a fix merged - see the macro "magit--with-temp-process-buffer", which magit now uses in place of "with-temp-buffer" for process-related purposes.

So the best option would be to land similar fixes in the upstream packages, and you can point to the magit example to support the case. See discussion in https://github.com/magit/magit/issues/4160 and the final PR https://github.com/magit/magit/pull/4169.

If `with-temp-buffer` were a function, then it could conceivably be advised by `envrc-mode`, but that's not the case. I'm a little wary of advising shell-command-to-string and call-process individually, but perhaps there's a way to do that safely using an `:around` advice. In particular, the magit issue linked above shows some of the shenanigans necessary to actually rebind that value so it takes effect. :-)

**Comment by purcell** [comment]
The following gets `shell-command-to-string` working:
```el
(defun envrc-propagate-environment (orig &rest args)
  (if envrc-mode
      (cl-letf* (((default-value 'process-environment) process-environment)
                 ((default-value 'exec-path) exec-path))
        (apply orig args))
    (apply orig args)))

(advice-add 'shell-command-to-string :around #'envrc-propagate-environment)
```
but of course in the general case you'd need to intercept the creation of any new temp buffers, because advising `call-process` as above would not work.

**Comment by znewman01** [comment]
My opinion (as a drive-by issue commenter, probably not even 2 cents worth :smile: )

1. I agree that it feels like a problem on behalf of the other libraries
2. but the default Emacs mechanisms seem to encourage the wrong thing here
3. so having a blessed workaround is really nice!'

I'll try that out on a couple of the places I've been running into this problem (e.g., some of the `org-mode` Latex export stuff) and report back.

**Comment by purcell** [comment]
+1. It probably wouldn't be hard to provide an all-purpose `:around` advice function that could be used to wrap any command, and then leave it up to users to apply it if they discover problems they can't patch upstream. I think the general case of magically making `call-process` work when indirectly invoked from a buffer that's in `envrc-mode` is probably not worth the complexity.

**Comment by Yevgnen** [comment]
Similar issue when trying to use `emacs-jupyter`.

https://github.com/nnicandro/emacs-jupyter/blob/6ce8d01e3a550a3268b415bf9d9b635d4dba5940/jupyter-env.el#L41-L51

**Comment by purcell** [comment]
> Similar issue when trying to use `emacs-jupyter`.

I've just published a tiny library called `inheritenv` to help elisp authors and Emacs end users deal with this sort of issue. Should be in MELPA shortly. https://github.com/purcell/inheritenv

You might like to submit a patch for that command so that it uses the `inheritenv` macro, and in the meantime you can use `inheritenv-add-advice` to override the command's behaviour.

**Comment by glasserc** [comment]
Sorry for leaving this issue alone for so long but I found some time yesterday to file an issue and open a PR on `rust-mode` (https://github.com/rust-lang/rust-mode/issues/446, https://github.com/rust-lang/rust-mode/pull/447). That was the problem that initially spurred this issue, so I wonder what we should do with this issue now. Should I (or someone else) file an issue with upstream emacs? Should we document this behavior somewhere (perhaps a "Known issues" or something)? Is there another action that this issue needs?

**Comment by purcell** [comment]
There's at least a route for folks to address this issue in related packages now, so I think we can close this.
