### ISSUE TITLE
Clarification on when envrc.el should be loaded?

### ISSUE THREAD

**Issue by zzantares** [purcell/envrc#23]
Hi Steve, I'm not an emacs savy by any means; while reading about when should `envrc.el` be loaded, more specifically this part here:

> **It's probably wise to do this late in your startup sequence: you normally want envrc-mode to be initialized in each buffer before other minor modes like flycheck-mode which might look for executables**. Counter-intuitively, this means that envrc-global-mode should be enabled after other global minor modes, since each prepends itself to various hooks.

Could you suggest a hook users could use to abide by this recommendation? Looking at [Emacs startup summary](https://www.gnu.org/software/emacs/manual/html_node/elisp/Startup-Summary.html#Startup-Summary) `window-setup-hook` runs right after `emacs-startup-hook` so that's the one we should use?

Thanks!

**Comment by purcell** [comment]
That's a good idea, but I'm not sure if I would have the best advice to offer. What I typically do is just prepend `envrc-global-mode` to `after-init-hook`, but late in the code loaded from `init.el`. I think that's the right hook to use for the purpose: I feel like others might be too late, ie. other process-using buffers might have been created by that stage. For instance, buffers might have been restored by that point via session.el/desktop.el.

**Comment by ZzAntares** [comment]
Thank you Steve, that clears it for me, since I use `use-package` then I think it is equivalent to put this late in the `init.el` file:

```elisp
(use-package envrc
  :hook (after-init . envrc-global-mode))
```

Please feel free to close the ticket.

**Comment by tmcgilchrist** [comment]
This snippet solved my issue with lsp-mode/dap-mode not getting the right environment with `envrc`. 
Is it accurate to include this in the Usage section of the Readme? https://github.com/purcell/envrc?tab=readme-ov-file#usage

**Comment by purcell** [comment]
Good idea: I've reworked that section of the README to make things clearer.

**Comment by tmcgilchrist** [comment]
Thanks @purcell for the documentation change and the library in general.
