### ISSUE TITLE
Peculiar error when saving .envrc

### ISSUE THREAD

**Issue by e-eight** [purcell/envrc#24]
Hi, 

I am using this package, and have set it up as mentioned in the README. Whenever I try to write a .envrc file using Emacs, I get the error message "peculiar error" in the echo area, and I am unable to save the .envrc file. I can write the file normally using other editors, and then envrc properly loads the environment as mentioned in the .envrc file. Any suggestions? Thanks!

**Comment by purcell** [comment]
Odd! The `envrc-file-mode` is based on `sh-mode`, so it's worth checking to see if you get the same error simply by creating and writing a `.sh` file in the same directory. I'm guessing this is somehow related to a process that is triggered at save time for shell scripts, e.g. a flymake/flycheck check, or a reformatter.

**Comment by e-eight** [comment]
Thanks! That worked. I use the `format-all` package, and it was trying to reformat the `.envrc` file but the `sh` reformatter was not installed.

**Comment by purcell** [comment]
Great!
