### ISSUE TITLE
direnv.el comparison notes in readme are partially incorrect

### ISSUE THREAD

**Issue by wbolster** [purcell/envrc#30]
👋🏼 `direnv.el` author here.

the current readme for this project makes these claims about `direnv.el`:

> * When switching to a buffer that is not "inside" a project with an
>   `.envrc` file, the buffer will see the last project's environment. I
>   would prefer it to see the default Emacs environment.
> 
> * When `direnv` fails to execute in the course of switching to a
>   buffer in a new project with an `.envrc` file (e.g. because that
>   `.envrc` file is disallowed), buffers in the new project will see the
>   environment variables from the previous project.

both claims are not (entirely) correct:

* `direnv.el` _unloads_ environments (reverting to default emacs env) when switching to a buffer outside a direnv-managed directory. only when switching to a buffer that is _not_ visiting a file (and hence not associated to a directory) the last used environment is retained; this is by design and very useful for things like scratch buffers, but also compilation buffers, etc.

* when `direnv.el` fails to execute `direnv` when switching buffers you will indeed see a warning/error, but the ‘active’ environment _is_ unloaded so there's no accidental carrying over of env vars from an unrelated project. this is standard `direnv` behaviour, and `direnv.el` inherits that.

**Comment by purcell** [comment]
Thanks, updated! And Happy New Year!

**Comment by wbolster** [comment]
thanks, changes look 👍🏼

all the best in 2021, oh wait, 2022 already 🙃

**Comment by purcell** [comment]
> oh wait, 2022 already

That can't be right...
