### ISSUE TITLE
Overriding ledger-toggle-current-transaction key binding

### ISSUE THREAD

**Issue by DamienCassou** [purcell/envrc#4]
How dare you override a ledger-mode binding?? Your own baby...

You may close the issue :-D.

**Comment by purcell** [comment]
LOL :-)

Yeah, hard to find a good place to put bindings. I might switch this to a prefix map so the user could change the prefix, but the code is usually a little more fiddly then...

**Comment by DamienCassou** [comment]
What about giving the user a chance to deactivate envrc keymap? I'm not modifying my direnvs much so I don't plan to reload often.

**Comment by purcell** [comment]
Probably users could just set or customize `envrc-mode-map` to `nil` or an empty map to achieve this?

**Comment by DamienCassou** [comment]
I did

```emacs
(unbind-key "C-c C-e" envrc-mode-map)
```

Maybe this is good enough.
