### ISSUE TITLE
Wrong type argument: integer-or-marker-p, nil

### ISSUE THREAD

**Issue by bbigras** [purcell/envrc#7]
I got `Wrong type argument: integer-or-marker-p, nil` when starting emacs. Not sure how to get a backtrace.

`emacs --debug-init` doesn't catch it.

I'm using `(envrc-global-mode)` and I tried loading it after lsp-mode.

Any ideas?

**Comment by purcell** [comment]
Hey, no, sorry I haven't seen this. Try setting `debug-on-error` to `t`, e.g. by putting `(setq debug-on-error t)` at the start of your `init.el`.

**Comment by bbigras** [comment]
Oh, it's related to org-roam after all. Sorry.

It's weird that I didn't have this error before enabling envrc (or maybe when I disabled direnv).

Sorry again, but thanks for the help. envrc is great. I really prefer a buffer-local solution.

https://github.com/org-roam/org-roam/issues/1074
