### ISSUE TITLE
Feature Request in the README

### ISSUE THREAD

**Issue by jgarte** [purcell/envrc#72]
> This library is like [the direnv.el package](https://github.com/wbolster/emacs-direnv), but sets all environment variables buffer-locally, while direnv.el changes the global set of environment variables after each command.

Would it be possible to give a quick TLDR/nod at why this fact is important? It would be helpful to quickly understand how that is important without having to dig deep into other packages to put two in two together/cross compare them. This would be especially helpful for newcomers/non-emacs afficionados trying to make a decision about whether to use this over another package or not 🥲

**Comment by purcell** [comment]
Thanks, I added a note, but I don't know if it will really help you much. :)

**Comment by jgarte** [comment]
That was great. Thanks a lot! Yes, it did help. It is much appreciated.
