### ISSUE TITLE
Missing `diff-mode` dependency for faces

### ISSUE THREAD

**Issue by aathn** [purcell/envrc#82]
The `envrc--summarise-changes` function uses faces `diff-changed`, `diff-added`, and `diff-removed`, but `envrc` does not require `diff-mode`.  This causes messages upon startup of the form
```
Invalid face reference: diff-changed [2 times]
Invalid face reference: diff-added
Invalid face reference: diff-changed [2 times]
...
```
if `diff-mode` was not previously loaded (on Emacs 29.1).

**Comment by purcell** [comment]
Thanks, I pushed a fix.
