### ISSUE TITLE
Use `.envrc` enviromnent for `project-compile`

### ISSUE THREAD

**Issue by benbellick** [purcell/envrc#87]
It seems that calling `project-compile` does not call the project-level compilation function from within the shell spawned via the `.envrc` file. It would be nice if this were the case, so that the compile commands can be identical to the ones used at the command line. 

Great package, thanks a ton!

**Comment by benbellick** [comment]
Probably related: 

`eglot` also seems unable to find binaries made available from the `.envrc` file. For example, I have the `ocamllsp` executable made available from within a shell spun up by direnv. But then when I invoke `M-x eglot` to try and start an lsp, the executable cannot be found. 

I guess that fundamentally the question is if processes related to the "project", e.g. starting eglot, running the project-level compilation, are also inside of the .envrc environment.

**Comment by benbellick** [comment]
Seems like calling `envrc-reload` fixed the problem, so never mind! Thanks 😄

**Comment by purcell** [comment]
Oh cool, I was going to say that I use ocamllsp via envrc without issues, glad you figured it out!
